# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kasplat.github.io/kesavankushalnagar.github.io/
title: :)
email: kesavan.kushalnagar@gmail.com
author: Kesavan Kushalnagar
description: > # "Write an awesome description for your new site here. 
  Computer Science Graduate from RIT. Software Engineer + Data Scientist.
copyright: 'Copyright &copy; 2018 Kesavan Kushalnagar. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:kesavan.kushalnagar@gmail.com
  - icon: github
    title: github
    url: https://github.com/kasplat
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/kesavan-kushalnagar/
  - icon: file-pdf-o
    title: resume
    url: https://resume.creddle.io/resume/ji477weh5rx
