# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kasplat.github.io/kesavankushalnagar.github.io/
title: :)
email: kesavan.kushalnagar@gmail.com
author: Kesavan Kushalnagar
description: > # "Write an awesome description for your new site here. 
  Computer Science Graduate from RIT. Software Engineer + Data Scientist.
copyright: 'Copyright &copy; 2018 Kesavan Kushalnagar. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/KKasplat
  - title: github
    url: https://github.com/kasplat
  - title: linkedin
    url: https://www.linkedin.com/in/kesavan-kushalnagar/
